import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import ganache from 'ganache';
import { ethers } from 'ethers';
import { deploy } from '../scripts/deploy.mjs';
const chain=ganache.server({chain:{chainId:1337,hardfork:'shanghai'},logging:{quiet:true}});await chain.listen(18545,'127.0.0.1');
const provider=new ethers.JsonRpcProvider('http://127.0.0.1:18545',undefined,{cacheTimeout:0});provider.pollingInterval=10;const admin=await provider.getSigner(0);const d=await deploy(admin);
fs.mkdirSync('data',{recursive:true});fs.writeFileSync('data/test-deployment.json',JSON.stringify(d));
process.env.PORT='3109';process.env.APP_ORIGIN='http://localhost:3109';process.env.RPC_URL='http://127.0.0.1:18545';process.env.DEPLOYMENT_FILE='data/test-deployment.json';process.env.SQLITE_PATH=':memory:';
const {server,db}=await import('../server/index.mjs');if(!server.listening)await new Promise(r=>server.once('listening',r));
const base='http://localhost:3109';
async function request(p,data,cookie,origin=base){const r=await fetch(base+p,{method:data?'POST':'GET',headers:{...(data?{'Content-Type':'application/json',Origin:origin}:{}),...(cookie?{Cookie:cookie}:{})},body:data?JSON.stringify(data):undefined});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
const signers=await Promise.all([0,1,2,3].map(i=>provider.getSigner(i)));const a=await Promise.all(signers.map(s=>s.getAddress()));const registry=new ethers.Contract(d.addresses.ParticipantRegistry,d.abi.ParticipantRegistry,admin);for(let i=1;i<=3;i++){await(await registry.setRole(a[i],i===3?2:1)).wait();await(await registry.setApproval(a[i],true)).wait();}
const keys=chain.provider.getInitialAccounts();async function login(i){const c=await request('/api/auth/challenge',{address:a[i]});const wallet=new ethers.Wallet(keys[a[i].toLowerCase()].secretKey);return request('/api/auth/verify',{address:a[i],signature:await wallet.signMessage(c.data.message)});}
let customer,other,auditor;
test('health and config do not expose private keys',async()=>{const h=await request('/health');assert.equal(h.status,200);const cfg=await request('/api/config');assert.equal(cfg.data.ready,true);assert.equal(JSON.stringify(cfg.data).includes('secretKey'),false);});
test('origin mismatches, invalid addresses and anonymous reads rejected',async()=>{assert.equal((await request('/api/auth/challenge',{address:a[1]},null,'https://evil.example')).status,403);assert.equal((await request('/api/auth/challenge',{address:'bad'})).status,400);assert.equal((await request('/api/snapshot')).status,401);});
test('wallet login consumes nonce; replay and forged signature rejected',async()=>{const c=await request('/api/auth/challenge',{address:a[1]});const wallet=new ethers.Wallet(keys[a[1].toLowerCase()].secretKey);const signature=await wallet.signMessage(c.data.message);assert.equal((await request('/api/auth/verify',{address:a[1],signature:'0x1234'})).status,401);const first=await request('/api/auth/verify',{address:a[1],signature});assert.equal(first.status,200);assert.match(first.cookie,/remit_session=/);customer=first.cookie;assert.equal((await request('/api/auth/verify',{address:a[1],signature})).status,401);other=(await login(2)).cookie;auditor=(await login(3)).cookie;});
test('snapshot reports on-chain role, not a browser-supplied role',async()=>{const x=await request('/api/snapshot',undefined,customer);assert.equal(x.status,200);assert.equal(x.data.role,1);assert.equal(x.data.approved,true);});
test('invoice data isolated by wallet and input validation enforced',async()=>{const created=await request('/api/invoices',{recipient:a[2],amount:'200',memo:'Supplier invoice'},customer);assert.equal(created.status,201);assert.equal((await request('/api/invoices',undefined,customer)).data.length,1);assert.equal((await request('/api/invoices',undefined,other)).data.length,0);assert.equal((await request('/api/invoices',{recipient:a[2],amount:'NaN',memo:'bad'},customer)).status,400);assert.equal((await request('/api/invoices',{recipient:a[2],amount:'200',memo:'bad'},auditor)).status,403);});
test('auditor can read audit; customer cannot grant themselves audit rights',async()=>{assert.equal((await request('/api/audit',undefined,customer)).status,403);assert.equal((await request('/api/audit',undefined,auditor)).status,200);});
test('receipts validate chain ownership; duplicates idempotent',async()=>{const token=new ethers.Contract(d.addresses.DemoUSD,d.abi.DemoUSD,signers[1]);const tx=await token.faucet();await tx.wait();assert.equal((await request('/api/receipts',{hash:tx.hash},other)).status,400);assert.equal((await request('/api/receipts',{hash:tx.hash},customer)).status,200);assert.equal((await request('/api/receipts',{hash:tx.hash},customer)).status,200);const rows=(await request('/api/audit',undefined,auditor)).data;assert.equal(rows.length,1);assert.equal(rows[0].tx,tx.hash);});
test('logout revokes session and static routes prevent traversal',async()=>{assert.equal((await request('/api/auth/logout',{},customer)).status,200);assert.equal((await request('/api/invoices',undefined,customer)).status,401);const r=await fetch(base+'/%2e%2e%2fpackage.json');assert.equal(r.status,404);const html=await fetch(base+'/');assert.equal(html.status,200);assert.match(html.headers.get('content-security-policy'),/frame-ancestors 'none'/);});
test.after(async()=>{await new Promise(resolve=>server.close(resolve));await db.close();await provider.destroy();await chain.close();});
